Application/blueprints/auth_views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for, current_app, send_from_directory
from flask_login import current_user, login_required, login_user, logout_user
import os
from werkzeug.security import check_password_hash, generate_password_hash
from ..objects.user import User
from ..objects.forms import SignUpForm, LoginForm
from ..dbmanager import get_db

bp = Blueprint("auth", __name__, url_prefix="/auth/")

@bp.route("/signup/", methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        flash('You Already Have an Account Here!', category='message')
        return redirect(url_for('profile.get_profile', email=current_user.email))
    form = SignUpForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            
            file = form.avatar.data
            avatar_dir = os.path.join(current_app.config['IMAGE_PATH'], form.email.data)
            if not os.path.exists(avatar_dir):
                os.makedirs(avatar_dir)
            avatar_path = os.path.join(avatar_dir, 'avatar.png')
            try:
                file.save(avatar_path)
            except Exception:
                flash('An error occurred with saving the avatar!', category='invalid')
                return redirect(url_for('auth.signup'))
            
            hash = generate_password_hash(form.password.data)
            user = User(form.email.data, form.name.data, hash)

            test_user = get_db().get_user(user.email)
            if test_user:
                flash('A User With That Email Already Exists!', category='invalid')
                return redirect(url_for('auth.signup'))
            else:
                get_db().insert_user(user)
                flash("User Added Successfully", category='valid')
            return render_template("index.html") 
        else:
            for error in form.errors:
                if error == 'avatar':
                    flash("Avatar Inputed Must Have a '.png' Extension!", category='invalid')
                else:
                    if error == 'name':
                        flash("Username Can't Contain any Spaces!", category='invalid')
                    elif len(form.errors) == 1:
                        flash(f"{error} is Invalid!", category='invalid')
                    else:
                        errors = ""
                        errors += f"{error.capitalize()}, "
                        flash(f"{errors} are Invalid!", category='invalid')
            return redirect(url_for('auth.signup'))
        
    elif request.method == 'GET':
        return render_template("signup.html", form=form)

@bp.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You Are Already Logged In!', category='message')
        return redirect(url_for('profile.get_profile', email=current_user.email))
    form = LoginForm()
    
    if request.method == 'POST':
        if form.validate_on_submit():
            email = form.email.data
            user = get_db().get_user(email)
            if user:
                password = form.password.data
                if check_password_hash(user.password, password):
                    login_user(user, remember=form.remember_me.data)
                    flash('Login Successful!', category='valid')
                    return redirect(url_for('index.index'))
                else:
                    flash('Email or Password Entered are Invalid!', category='invalid')
                    return redirect(url_for('auth.login'))
            else:
                flash("Email or Password Entered are Invalid!", category='invalid')
                return redirect(url_for('auth.login'))
        else:
            for error in form.errors:
                if error == 'avatar':
                    flash("Avatar Inputed Must Have a '.png' Extension!", category='invalid')
                else:
                    if len(form.errors) == 1:
                        flash(f"{error} is Invalid!", category='invalid')
                    else:
                        errors = ""
                        errors += f"{error.capitalize()}, "
                        flash(f"{errors} are Invalid!", category='invalid')
            return redirect(url_for('index.index'))
    elif request.method == 'GET':
        return render_template('login.html', form=form)
    
@bp.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('Successfully Logged Out!', category='valid')
    return redirect(url_for('index.index'))

@bp.route('/avatar/<email>/avatar.png/')
@login_required
def get_avatar(email):
    if current_user.blocked and current_user.email != email:
        flash("You Have Been Blocked by an Admin, so Viewing this Page is Not Allowed!", category='invalid')
        return redirect(url_for('profile.get_profile', email=current_user.email))
    dir = os.path.join(current_app.config['IMAGE_PATH'], email)
    return send_from_directory(dir, 'avatar.png')

Application/blueprints/domains_view.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import current_user, login_required

from ..objects.domain import Domain
from ..dbmanager import get_db

from ..objects.forms import DomainForm

bp = Blueprint("domains", __name__, url_prefix="/domains/")

@bp.route("/", methods=['GET', 'POST'])
def show_domains():
    if current_user.is_active:
        if current_user.blocked:
            flash('You Have Been Blocked by an Admin!', category='invalid')
            return redirect(url_for('profile.get_profile', email=current_user.email))
        
    domains, prev_page, next_page = get_db().get_all_domains(page_size=100)
    if domains:
        return render_template('domains.html', domains=domains)
    
    flash("No domains", category='invalid')
    return render_template('index.html')

@bp.route("/<int:domain_id>/", methods=['GET'])
def show_domain(domain_id):
    domain = get_db().get_domain(domain_id)
    courses = get_db().get_courses_by_domain(domain_id)

    if domain:
        return render_template('domains.html', domain=domain, courses=courses)
    
    flash("No domain with this id", category='invalid')
    return redirect(url_for('domains.show_domains'))

@bp.route('/add/', methods=['GET', 'POST'])
@login_required
def add_domain():
    form = DomainForm()
    
    if request.method == 'GET':
        return render_template('modify_domain.html', form=form)
    
    elif request.method == 'POST':
        if form.validate_on_submit():
            matchingDomain = False
            domains, prev_page, next_page = get_db().get_all_domains(page_size=100)

            for domain in domains:
                if domain.name == form.name.data:
                    matchingDomain = True
                    flash("A Domain with the same name already exists")

            if not matchingDomain:
                dom = Domain(form.name.data, form.description.data)
                try:
                    get_db().add_domain(dom)
                    flash("Added Domain: " + dom.name, category='valid')
                except Exception:
                    flash('Error adding domain', category='invalid')

    return redirect(url_for('domains.show_domains'))

@bp.route("/edit/<int:dom_id>/", methods=['GET', 'POST'])
@login_required
def edit_domain(dom_id):
    dom = get_db().get_domain(dom_id)
    form = DomainForm(obj=dom)

    if request.method == 'GET':
        return render_template('modify_domain.html', form=form, domain=dom)
    
    elif request.method == 'POST':
        if form.validate_on_submit():

            if form.name.data.isnumeric() or form.description.data.isnumeric():
                flash("Unsuccesfully Edited Domain", category='invalid')
                return redirect(url_for('domains.show_domains'))
            
            dom_name = form.name.data
            dom_desc = form.description.data

            if form.name.data is None:
                dom_name = dom.name
            if form.description.data is None:
                dom_desc = dom.description
            
            domain = Domain(dom_name, dom_desc)
            domain.id = dom.id
            try:
                get_db().modify_domain(domain)
                flash("Edited Domain: " + domain.name, category='valid')
            except Exception:
                flash('Error editing domain', category='invalid')
        
        else:
            flash("Domain form is not valid!", category='invalid')
    
    return redirect(url_for('domains.show_domains'))

@bp.route('/delete/<int:dom_id>')
@login_required
def delete_domain(dom_id):
    try:
        get_db().delete_domain(int(dom_id))
        flash(f"Domain {dom_id} has been deleted along with its courses", category='valid')
    except Exception:
        flash('Error deleting domain', category='invalid')
    return redirect(url_for('domains.show_domains'))

Application/blueprints/home_view.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user

from Application.objects.forms import SearchForm

from ..dbmanager import get_db

bp = Blueprint('index', __name__, url_prefix='/')

@bp.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_active:
        if current_user.blocked:
            flash('You Have Been Blocked by an Admin!', category='invalid')
            return redirect(url_for('profile.get_profile', email=current_user.email))
        
    form = SearchForm()

    if request.method == 'GET':
        return render_template('index.html', form=form)
    
    elif request.method == 'POST':
        if form.validate_on_submit():

            if form.query.data:
                return redirect(url_for('index.search_db'
                                        , search_query=form.query.data))
    
    return render_template('index.html', form=form)

@bp.route('/terms/')
def show_terms():
    terms = get_db().get_all_terms()
    return render_template('terms.html', terms=terms)

@bp.route("/terms/<int:term_id>/", methods=['GET', 'POST'])
def show_courses_by_term(term_id):
    courses = get_db().get_courses_by_term(term_id)

    if courses:
        return render_template('terms.html', courses=courses, term=term_id)
    
    flash("No courses by this term", category='invalid')
    return redirect(url_for('index.show_terms'))

@bp.route("/search/<string:search_query>/")
def search_db(search_query):
    try:
        courses, competencies, elements, domains = get_db().search_all(search_query)
        return render_template('search_results.html', courses=courses, competencies=competencies, elements=elements, domains=domains, search=search_query)
    except Exception:
        flash('Error Searching', category='invalid')
        return redirect(url_for('index.index'))

Application/blueprints/user_admins_views.py
import os
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash

from ..dbmanager import get_db
from ..objects.user import User

from ..objects.forms import DeleteUserAdminForm, MoveUserAdminForm, SignUpForm

bp = Blueprint('user_admins', __name__, url_prefix='/user_admins/')

@bp.route('/')
@login_required
def list_user_admins():
    if current_user.group != 'Admin':
        flash("You Don't Have Permissions to View this Page!", category='invalid')
        return redirect(url_for('index.index'))
    user_admins = get_db().get_user_admins()
    return render_template('user_admins.html', user_admins=user_admins)

@bp.route('/add/', methods=['GET', 'POST'])
@login_required
def add_user_admin():
    form = SignUpForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            
            file = form.avatar.data
            avatar_dir = os.path.join(current_app.config['IMAGE_PATH'], form.email.data)
            if not os.path.exists(avatar_dir):
                os.makedirs(avatar_dir)
            avatar_path = os.path.join(avatar_dir, 'avatar.png')
            try:
                file.save(avatar_path)
            except Exception:
                flash('An error occurred with saving the avatar!', category='invalid')
                return redirect(url_for('user_admins.list_user_admins'))
            
            hash = generate_password_hash(form.password.data)
            user = User(form.email.data, form.name.data, hash)

            test_user = get_db().get_user(user.email)
            if test_user:
                flash('A User With That Email Already Exists!', category='invalid')
                return redirect(url_for('user_admins.list_user_admins'))
            else:
                get_db().insert_user(user, 'User Admin')
                flash("User Admin Added Successfully", category='valid')
                user_admins = get_db().get_user_admins()
                return render_template("user_admins.html", form=form, user_admins=user_admins)
        else:
            for error in form.errors:
                if error == 'avatar':
                    flash("Avatar Inputed Must Have a '.png' Extension!", category='invalid')
                else:
                    if len(form.errors) == 1:
                        flash(f"{error} is Invalid!", category='invalid')
                    else:
                        errors = ""
                        errors += f"{error.capitalize()}, "
                        flash(f"{errors} are Invalid!", category='invalid')
            return redirect(url_for('user_admins.list_user_admins'))
        
    elif request.method == 'GET':
        return render_template("add_user.html", form=form, user_type='User Admin')
    
@bp.route('/move/', methods=['GET', 'POST'])
@login_required
def move_user_admin():
    if not get_db().get_user_admins():
        flash('There Are No User Admins to Move!', category='message')
        return redirect(url_for('user_admins.list_user_admins'))
    form = MoveUserAdminForm()
    form.users.choices = [user_admin.email for user_admin in get_db().get_user_admins()]
    form.groups.choices = ['Member', 'Admin']

    if request.method == 'POST' and form.validate_on_submit():
        user_admin = get_db().get_user(form.users.data)
        if user_admin:
            get_db().move_member(user_admin.email, form.groups.data)
            flash(f'User Admin Successfully Moved to {form.groups.data} Group!', category='valid')
            user_admins = get_db().get_user_admins()
            form.users.choices = [user_admin.email for user_admin in user_admins]
            return render_template('user_admins.html', form=form, user_admins=user_admins)
    elif request.method == 'GET':
        return render_template('move_user.html', form=form, user_type='User Admin')
    
@bp.route('/delete/', methods=['GET', 'POST'])
@login_required
def delete_user_admin():
    if not get_db().get_user_admins():
        flash('There Are No User Admins to Delete!', category='message')
        return redirect(url_for('user_admins.list_user_admins'))
    form = DeleteUserAdminForm()
    # assigns select options by looping through the members and adding the emails to the select
    form.users.choices = [user_admin.email for user_admin in get_db().get_user_admins()]

    if request.method == 'POST' and form.validate_on_submit():
        user_admin = get_db().get_user(form.users.data)
        if user_admin:
            get_db().delete_user(user_admin.email)
            flash('User Admin Successfully Deleted!', category='valid')
            user_admins = get_db().get_user_admins()
            return render_template('user_admins.html', user_admins=user_admins)
    elif request.method == 'GET':
        return render_template('delete_user.html', form=form, user_type='User Admin')

Application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="{{ url_for( 'static', filename='style.css' ) }}">
    <script defer type="text/javascript" src="{{ url_for('static', filename='script.js') }}"></script>
</head>
<body>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flashes">
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <nav>
        <ul>
            {% if current_user.blocked %}
                <li>
                    <a id="small_avatar_a" href="{{ url_for('profile.get_profile', email=current_user.email) }}">
                        <img id="small_avatar" src="{{ url_for('auth.get_avatar', email=current_user.email) }}" alt="small_profile_pic">{{ current_user.name }}
                    </a>
                </li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% else %}
                <li><a href="{{ url_for( 'index.index' ) }}">Home</a></li>

                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('members.list_members') }}">Members Dashboard</a></li>
                    {% if current_user.group == 'Admin' %}
                        <li><a href="{{ url_for('user_admins.list_user_admins') }}">User Admin Dashboard</a></li>
                    {% endif %}
                    {% if current_user.group == 'Admin' %}
                        <li><a href="{{ url_for('admins.list_admins') }}">Admins Dashboard</a></li>
                    {% endif %}
                    <li>
                        <a id="small_avatar_a" href="{{ url_for('profile.get_profile', email=current_user.email) }}">
                            <img id="small_avatar" src="{{ url_for('auth.get_avatar', email=current_user.email) }}" alt="small_profile_pic">{{ current_user.name }}
                        </a>
                    </li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.signup') }}">Sign Up</a></li>
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>

    {% block content %}

    {% endblock %}
    
</body>
</html>

Application/templates/competencies.html
{% extends 'base.html' %}

{% block title %}
    Competencies
{% endblock %}

{% block content %}
    <div id="competencies_page_content">
        {% if elements_array %}
            <h1 id="competencies_page_heading">Competency</h1>
        {% else %}
            <h1 id="competencies_page_heading">Competencies</h1>
            {% if current_user.is_authenticated %}
                <a href="{{url_for('competencies.add_competency')}}"><input type="button" id="add_course_btn" value="Add Competency" /></a>
            {% endif %}
        {% endif %}
        {% for competency in competencies %}
            <div class="competency_info">
                <a href="{{url_for('competencies.show_competency_elements', comp_id=competency.id)}}" class="invisible_link"><h2>{{ competency.name }}</h2></a>
                <a href="{{url_for('competencies.show_competency_elements', comp_id=competency.id)}}" class="invisible_link"><h3>{{ competency.id }}</h3></a>
                <h3>{{ competency.type }}</h3>
                <h3 class="competency_achievement">{{ competency.achievement }}</h3>
                {% if current_user.is_authenticated %}
                    <div class="competency-add-edit-del-buttons">
                        <a href="{{url_for('competencies.edit_competency', comp_id=competency.id)}}"><input type="button" value="Edit Competency" /></a>
                        <a href="{{url_for('competencies.delete_competency', comp_id=competency.id)}}"><input type="button" value="Delete Competency" /></a>
                    </div>
                {% endif %}
            </div>
            
            <br/>
            <hr class="white_line">
            
            {% if elements_array %}
                
                {% if current_user.is_authenticated %}
                    <a href="{{url_for('elements.add_element')}}"><input type="button" class="add_element_btn" value="Add Element" /></a>
                {% endif %}

                {% for elements in elements_array %}
                    {% for element in elements %}
                        {% if competency.id == element.competency_id %}
                            <div class="criteria_content">
                                <h3 class="underline">Criteria {{ element.order }}</h3>
                                <h4> {{ element.name }}</h4>
                                <p>{{ element.criteria }}</p>
                                {% if current_user.is_authenticated %}
                                    <div class="element-add-edit-del-buttons">
                                        <a href="{{url_for('elements.edit_element', elem_id=element.id)}}"><input type="button" class="edit_delete_element_btn" value="Edit Element" /></a>
                                        <a href="{{url_for('elements.delete_element', elem_id=element.id)}}"><input type="button" class="edit_delete_element_btn" value="Delete Element" /></a>
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

Application/templates/course.html
{% extends 'base.html' %}

{% block title %}
    {{ course.title }}
{% endblock %}

{% block content %}
    <h1 id="course_page_heading">{{ course.title }}</h1>
    <div id="course_info">
        <a class="invisible_link" href="{{url_for('index.show_courses_by_term', term_id=course.term_id)}}">
            <p><span class="underline">Term:</span> {{ course.term_id }}</p>
        </a>
        <a class="invisible_link" href="{{url_for('domains.show_domain', domain_id=course.domain_id)}}">
            <p><span class="underline">Domain:</span> {{ domain.name }}</p>
        </a>
        <p><span class="underline">Theory Hours:</span> {{ course.theory_hours }}</p>
        <p><span class="underline">Lab Hours:</span> {{ course.lab_hours }}</p>
        <p><span class="underline">Work Hours:</span> {{ course.work_hours }}</p>
        <p><span class="underline">Description:</span></p>
        <p id="description">{{ course.description }}</p>
        
        {% if current_user.is_authenticated %}
            <div id="course_edit_del_buttons">
                <a href="{{url_for('courses.edit_course', course_id=course.id)}}"><input type="button" class="course_btns" value="Edit" /></a>
                <a href="{{url_for('courses.delete_course', course_id=course.id)}}"><input type="button" class="course_btns" value="Delete" /></a>
            </div>
        {% endif %}

    </div>

    <br/>
    <hr class="white_line">

    <div id="course_elements">
        <h2>{{ course.title }}'s Competency Elements:</h2>
        {% if current_user.is_authenticated %}
            <a href="{{url_for('courses.add_course_element', course_id=course.id)}}"><input type="button" class="add_element_btn" value="Add Element" /></a>
        {% endif %}
        {% for element in elements %}
            <div class="element">
                <h3><a href="{{url_for('competencies.show_competency_elements', comp_id=element.competency_id)}}", class="invisible_link"><span class="underline">Competency ID:</span></a> {{ element.competency_id | safe }}</h3>
                <h4><span class="underline">Order:</span> {{ element.order | safe }}</h4>
                <h4><span class="underline">Name:</span> {{ element.name | safe }}</h4>
                <h4><span class="underline">Hours:</span> {{ element.hours | safe}}</h4>
                <h4><span class="underline">Criteria:</span></h4>
                <p class="criteria">{{ element.criteria | safe }}</p>
                {% if current_user.is_authenticated %}
                    <div class="element_btns">
                        <a href="{{url_for('courses.edit_course_element', course_id=course.id, elem_id=element.id)}}"><input type="button" value="Edit Hours" /></a>
                        <a href="{{url_for('courses.delete_course_element', course_id=course.id, elem_id=element.id)}}"><input type="button" value="Delete Course Element" /></a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

Application/templates/delete_user.html
{% extends 'base.html' %}

{% block title %}
    Delete {{ user_type }}
{% endblock %}

{% block content %}
    <div id="delete_user_content">
        <h2>Delete {{ user_type }} Form</h2>
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.users.label }} {{ form.users() }}
            <input type="submit" value="Delete {{ user_type }}">
        </form>
    </div>
{% endblock %}

Application/templates/domains.html
{% extends 'base.html' %}

{% block title %}
    {% if domain %}    
        {{ domain.name }}
    {% else %}
        Domains
    {% endif %}
{% endblock %}

{% block content %}
    <div id="domain_page_content">
        <h1 id="domain_page_heading">
            {% if domain %}    
                Domain
            {% else %}
                Domains
            {% endif %}
        </h1>
        {% if current_user.is_authenticated %}
            <a href="{{url_for('domains.add_domain')}}">
                <input id="add_domain_btn" type="button" value="Add Domain" />
            </a>
        {% endif %}
        
        {% for domain in domains %}
            <div class="domain">
                <a class="invisible_link" href="{{url_for('domains.show_domain', domain_id=domain.id)}}">
                    <h2>{{ domain.name }}</h2>
                </a>
                <p>{{ domain.description }}</p>
                {% if current_user.is_authenticated %}
                    <div id="edit_delete_domain">
                        <a href="{{url_for('domains.edit_domain', dom_id=domain.id)}}">
                            <input type="button" value="Edit Domain" />
                        </a>
                        <a href="{{url_for('domains.delete_domain', dom_id=domain.id)}}">
                            <input type="button" value="Delete Domain" />
                        </a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}

        {% if domain -%}
            <div class="domain">
                <h2>{{ domain.name }}</h2>
                <p>{{ domain.description }}</p>
            </div>

            <div id="domain_courses_div">
                {% if courses %}
                    <h3>Courses In This Domain</h3>

                    {% for course in courses %}
                        <a class="invisible_link" href="{{url_for('courses.show_course', course_id=course.id)}}">
                            <p>{{ course.id }}</p>
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        {%- endif %}
    </div>
{% endblock %}

Application/templates/logout.html
{% extends 'base.html' %}
{% block title %}
    Log Out
{% endblock %}
{% block content %}
    <h1>Logged Out!</h1>
{% endblock %}

Application/templates/search_results.html
{% extends 'base.html' %}

{% block title%}
    Search Results
{% endblock %}

{% block content %}
    <h1 class="search_results_heading">Search Results For: {{ search | safe }}</h1>

    {% if not (courses and competencies and elements and domains) %}
        <h2 class="search_results_heading">No Results were Returned with That Query!</h2>
    {% else %}
        <div id="search_container">
            {% for course in courses %}
            <h2 id="course_page_heading">{{ course.title }}</h2>
            <div id="course_info">
                <a class="invisible_link" href="{{url_for('index.show_courses_by_term', term_id=course.term_id)}}">
                    <p><span class="underline">Term:</span> {{ course.term_id }}</p>
                </a>
                <a class="invisible_link" href="{{url_for('domains.show_domain', domain_id=course.domain_id)}}">
                    <p><span class="underline">Domain:</span> {{ course.domain_id }}</p>
                </a>
                <p><span class="underline">Theory Hours:</span> {{ course.theory_hours }}</p>
                <p><span class="underline">Lab Hours:</span> {{ course.lab_hours }}</p>
                <p><span class="underline">Work Hours:</span> {{ course.work_hours }}</p>
                <p><span class="underline">Description:</span></p>
                <p id="description">{{ course.description }}</p>
            </div>

            <hr class="white_line">
        {% endfor %}

        {% for competency in competencies %}
            <div class="competency_info">
                <a href="{{url_for('competencies.show_competency_elements', comp_id=competency.id)}}" class="invisible_link"><h2>{{ competency.name }}</h2></a>
                <a href="{{url_for('competencies.show_competency_elements', comp_id=competency.id)}}" class="invisible_link"><h3>{{ competency.id }}</h3></a>
                <h3>{{ competency.type }}</h3>
                <p class="competency_achievement">{{ competency.achievement }}</p>
            </div>

            <hr class="white_line">
        {% endfor %}

        {% for element in elements %}
            <div class="criteria_content">
                <h3 class="underline">Criteria {{ element.order }}</h3>
                <h4>{{ element.name }}</h4>
                <p>{{ element.criteria }}</p>
            </div>
        {% endfor %}

        {% for domain in domains %}
            <div class="domain">
                <a class="invisible_link" href="{{url_for('domains.show_domain', domain_id=domain.id)}}">
                    <h2>{{ domain.name }}</h2>
                </a>
                <p>{{ domain.description }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

Application/templates/user_admins.html
{% extends 'base.html' %}

{% block title %}
    User Admins Dashboard
{% endblock %}

{% block content %}
    <h1 id="user_admins_heading">List of User Admins</h1>
    <div class="users_toolbar">
        <button>
            <a href="{{ url_for('user_admins.add_user_admin') }}">Add User Admin</a>
        </button>
        <button>
            <a href="{{ url_for('user_admins.delete_user_admin') }}">Delete User Admin</a>
        </button>
        <button>
            <a href="{{ url_for('user_admins.move_user_admin') }}">Move User Admin</a>
        </button>
    </div>
    <ul class="users_list">
        {% if user_admins|length == 0 %}
            <h1>There Aren't Any User Admins Created!</h1>
        {% endif %}
        {% for user_admin in user_admins %}
            <div class="member_info">
                <a href="{{ url_for('profile.get_profile', email=user_admin.email) }}" class="invisible_link user_info">
                    <img class="user_list_avatar" src="{{ url_for('auth.get_avatar', email=user_admin.email) }}">
                    {{ user_admin.name }} <span class="member_email">&nbsp;{{ user_admin.email }}</span></a>
            </div>
        {% endfor %}
    </ul>
{% endblock %}